// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgVpmw1ZbopRQRrEgf37cqa--tALasos',
    appId: '1:606993902522:web:578a5dfccbedc4e7778b83',
    messagingSenderId: '606993902522',
    projectId: 'ethiostreetfix-d73f9',
    authDomain: 'ethiostreetfix-d73f9.firebaseapp.com',
    storageBucket: 'ethiostreetfix-d73f9.firebasestorage.app',
    measurementId: 'G-YWV201GY5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YH49XNK9rpArdeLRRdaASyvdnAl6Qbk',
    appId: '1:606993902522:android:9b6257fb67dbb3fa778b83',
    messagingSenderId: '606993902522',
    projectId: 'ethiostreetfix-d73f9',
    storageBucket: 'ethiostreetfix-d73f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3PErZy6CGvV5PudDoJ725Vxen1cPPG0',
    appId: '1:606993902522:ios:bc74890324af838f778b83',
    messagingSenderId: '606993902522',
    projectId: 'ethiostreetfix-d73f9',
    storageBucket: 'ethiostreetfix-d73f9.firebasestorage.app',
    iosBundleId: 'com.example.ethioStreetFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-3PErZy6CGvV5PudDoJ725Vxen1cPPG0',
    appId: '1:606993902522:ios:bc74890324af838f778b83',
    messagingSenderId: '606993902522',
    projectId: 'ethiostreetfix-d73f9',
    storageBucket: 'ethiostreetfix-d73f9.firebasestorage.app',
    iosBundleId: 'com.example.ethioStreetFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSgVpmw1ZbopRQRrEgf37cqa--tALasos',
    appId: '1:606993902522:web:96d2f7fbd4b8a8c3778b83',
    messagingSenderId: '606993902522',
    projectId: 'ethiostreetfix-d73f9',
    authDomain: 'ethiostreetfix-d73f9.firebaseapp.com',
    storageBucket: 'ethiostreetfix-d73f9.firebasestorage.app',
    measurementId: 'G-0KLHFEZMXP',
  );
}
